### ISSUE TITLE
Add WikiMedia bird photo URLs to README.md

### ISSUE THREAD

**Issue by ohiofi** [BradleyCodeU/BirdPhotoURLs#6]
Collecting bird photo URLs from WikiMedia for an educational game

Currently the Bird Game has about 12 birds. We'd like to add more, but looking up images is a lot of work. YOU CAN HELP!

Pick a bird from the README.md list (birds marked -- are MOST NEEDED)

Google the name of the bird and site:wikimedia.org

For example...
american crow site:wikimedia.org
Find a GOOD IMAGE of the bird.

Not blurry
You can see the full body of the bird (not just the head)
Landscape or square image (not portrait orientation)
Copy/paste the URL for a good image below the bird name. The URL should begin with https://upload.wikimedia.org/ ...etc.

**Comment by a-arham-x** [comment]
I can work on this issue. Please assign this issue to me.

**Comment by ohiofi** [comment]
Thanks for offering to help! You are welcome to contribute a pull request and I will label your pull request with hacktoberfest-accepted. I would prefer to leave the issue open so that other people can contribute as well.

**Comment by Divyansh200102** [comment]
i want to contribute .please assign it to me @ohiofi
